# Pandas Series and Dataframe

Complete the tasks listed below. You can submit the completed lab until 11:59 PM in the night.

<u>Requirement:</u><br>
Do your best to write Pythonic code instead of the traditional programming code.

<u>Hint:</u><br>
For Tasks 1 - 5, you would need to create a Series first using __pd.Series__

### Task 1 (1 mark)

Import the necessary libraries. Then write Pandas code that takes in the Series __['215', '169', 'Series', '400', '180']__ and converts it to a Numpy array.

In [62]:
### Write your code below this comment.
import pandas as pd
import numpy as np

ser_1 = pd.Series(['215', '169', 'Series', '400', '180'])

arr_1 = np.array(ser_1)

arr_1


array(['215', '169', 'Series', '400', '180'], dtype=object)

### Task 2 (1 mark)

Write a Pandas program that takes in the Series __['215', '169', 'Series', '400', '180']__ and converts it into a numeric type Series.

<u>Hint:</u><br>
`pd.to_numeric()`

In [63]:
### Write your code below this comment.
ser_2 = pd.Series(['215', '169', 'Series', '400', '180'])
Ser_num_1=pd.to_numeric(ser_2,errors='coerce')
Ser_num_1

0    215.0
1    169.0
2      NaN
3    400.0
4    180.0
dtype: float64

### Task 3 (1 mark)

Write Pandas code that creates a Series from the string __'23465613185695243632244'__ and then filters the elements of this Series at the indices __3__, __5__, __8__, __14__, and __22__.

<u>Hint:</u><br>
`Series.take()`

In [64]:
### Write your code below this comment.
str_data_1 = '23465613185695243632244'
ser_3 = pd.Series(list(str_data_1))

filter_1 = [3, 5, 8, 14, 22]

filtered_Data_1 = ser_3.take(filter_1)

print(filtered_Data_1)


3     6
5     6
8     1
14    2
22    4
dtype: object


### Task 4 (1 mark)

Write Pandas code that takes in two Series s1 = __[1, 2, 3, 4, 5]__ and s2 = __[2, 4, 6, 8, 10]__ and creates a new Series which contains only those items of s1 not present in s2.

In [65]:
### Write your code below this comment.
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([2, 4, 6, 8, 10])

filtered_s1 = s1[~s1.isin(s2)]

print(filtered_s1)

0    1
2    3
4    5
dtype: int64


### Task 5 (1 mark)

Write Pandas code that takes in two Series __[2, 4, 6, 8, 10]__ and __[1, 3, 5, 7, 10]__ and returns a boolean Series each time telling whether the elements of Series 1 are equal to Series 2, greater than Series 2, or less than Series 2.

In [66]:
### Write your code below this comment.


s1 = pd.Series([2, 4, 6, 8, 10])
s2 = pd.Series([1, 3, 5, 7, 10])


series_eq = s1 == s2

series_gq = s1 > s2

series_ls = s1 < s2

comp_data = pd.DataFrame({'Equal to': series_eq, 'Greater than': series_gq, 'Less than': series_ls})
res_data=pd.concat([s1, s2, comp_data], axis=1)

res_data.columns = ['Series 1', 'Series 2', 'Equal to', 'Greater than', 'Less than']

print(res_data)


   Series 1  Series 2  Equal to  Greater than  Less than
0         2         1     False          True      False
1         4         3     False          True      False
2         6         5     False          True      False
3         8         7     False          True      False
4        10        10      True         False      False


---

The following tasks pertain to the **Boston Housing Price dataset**. The Boston house-price data has been used in many machine learning papers that address regression problems. You will read the data from a CSV file into a Pandas DataFrame and do some basic data wrangling with it. You can do that using the __pd.read_csv()__ function.

Following are the details of the attributes of this dataset for your reference. You may have to refer to them while completing the tasks below.

* **CRIM**: per capita crime rate by town
* **ZN**: proportion of residential land zoned for lots over 25,000 sq.ft.
* **INDUS**: proportion of non-retail business acres per town
* **CHAS**: Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
* **NOX**: nitric oxides concentration (parts per 10 million)
* **RM**: average number of rooms per dwelling
* **AGE**: proportion of owner-occupied units built prior to 1940
* **DIS**: weighted distances to five Boston employment centres
* **RAD**: index of accessibility to radial highways
* **TAX**: full-value property-tax rate per 10,000 dollars
* **PTRATIO**: pupil-teacher ratio by town
* **B**: 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
* **LSTAT**: % of lower status of the population
* **PRICE**: Median value of owner-occupied homes in $1000's

### Task 6 (0.5 mark)

Read in the Boston housing data set (given as a .csv file) from the included __data__ directory as the dataframe __df__.

In [67]:
### Write your code below this comment.
df=pd.read_csv('/content/Boston_housing.csv')
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  PRICE  
0       15.3  396.90   4.98   24.0  
1       17.8  396.90   9.14   21.6  
2       17.8  392.83   4.03   34.7  
3       18.7  394.63   2.94   33.4  
4       18.7  396.90   5.33   36.2  
..       ...     ...    ...    ...  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9  

[506 rows x 14 columns]

In [68]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2

### Task 7 (0.5 mark)

Display the first 10 rows of your dataframe.

In [69]:
### Write your code below this comment.
df.head(n=10)

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575   65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421   78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185   61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998   45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222     18.7   
5  0.02985   0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222     18.7   
6  0.08829  12.5   7.87     0  0.524  6.012   66.6  5.5605    5  311     15.2   
7  0.14455  12.5   7.87     0  0.524  6.172   96.1  5.9505    5  311     15.2   
8  0.21124  12.5   7.87     0  0.524  5.631  100.0  6.0821    5  311     15.2   
9  0.17004  12.5   7.87     0  0.524  6.004   85.9  6.5921    5  311     15.2   

        B  LSTAT  PRICE  
0  396.90   4.98   24.0  
1  396.90   9.14   21.6  
2  392.83   4.03   34.7  
3  394.63   2.94   33.4  
4  396.90   5.33   36.2  
5  394.12   5.21   28.7  
6  395.60  12.43   22.9  
7  396.90  19.15   27.1  
8  386.63  29.93   16.5  
9  386.71  17.10   18.9

### Task 8 (1.5 marks)

Access row three (index 2) and columns `CRIM` and `PRICE` using whatever indexing method you like. Then explain why the row appears as a column and how you could possibly rectify that?

In [70]:
### Write your code below this comment.
sel_Data_1=df.loc[3,['CRIM','PRICE']]
sel_Data_1

CRIM      0.03237
PRICE    33.40000
Name: 3, dtype: float64

As we used loc to access the row 3 it shows the values as Series index and to rectify and change it to rows we can place the loc in [] to row as below.

In [71]:
data_frame_2=df.loc[[3],['CRIM','PRICE']]
data_frame_2

CRIM  PRICE
3  0.03237   33.4

### Task 9 (0.5 mark)

In total, how many records are there?

In [77]:
### Write your code below this comment.
df.shape[0]

506

### Task 10 (1.5 marks)

Create a smaller DataFrame __df1__ from __df__ that does not include the columns `CHAS`, `NOX`, `B`, and `LSTAT`. Once you have done that, confirm that the number of columns in the smaller dataframe is less by 4 compared with the original dataframe.

In [73]:
### Write your code below this comment.
print('Before dataframe length of columns',df.shape[1])

Before dataframe length of columns 14


In [74]:
df1=df.drop(columns=['CHAS','NOX','B','LSTAT'],axis=1)

print('After dataframe length of columns',df1.shape[1])

After dataframe length of columns 10


### Task 11 (0.5 mark)

Check the last 7 records of the new DataFrame __df1__ you just created.

In [75]:
### Write your code below this comment.
df1.tail(n=7)

CRIM   ZN  INDUS     RM   AGE     DIS  RAD  TAX  PTRATIO  PRICE
499  0.17783  0.0   9.69  5.569  73.5  2.3999    6  391     19.2   17.5
500  0.22438  0.0   9.69  6.027  79.7  2.4982    6  391     19.2   16.8
501  0.06263  0.0  11.93  6.593  69.1  2.4786    1  273     21.0   22.4
502  0.04527  0.0  11.93  6.120  76.7  2.2875    1  273     21.0   20.6
503  0.06076  0.0  11.93  6.976  91.0  2.1675    1  273     21.0   23.9
504  0.10959  0.0  11.93  6.794  89.3  2.3889    1  273     21.0   22.0
505  0.04741  0.0  11.93  6.030  80.8  2.5050    1  273     21.0   11.9

In [76]:
%%shell
jupyter nbconvert --to html /content/Lab05.ipynb

[NbConvertApp] Converting notebook /content/Lab05.ipynb to html
[NbConvertApp] Writing 651359 bytes to /content/Lab05.html
